services:

  # Orthanc - OpenMRS integration service
  eip-openmrs-orthanc:
    depends_on:
      env-substitution:
        condition: service_completed_successfully
      openmrs:
        condition: service_healthy
      mysql:
        condition: service_started
      orthanc:
        condition: service_started
    environment:
      - EIP_DB_NAME_ORTHANC=${EIP_DB_NAME_ORTHANC}
      - EIP_DB_USER_ORTHANC=${EIP_DB_USER_ORTHANC}
      - EIP_DB_PASSWORD_ORTHANC=${EIP_DB_PASSWORD_ORTHANC}
      - OPENMRS_URL=http://openmrs:8080/openmrs
      - ORTHANC_URL=http://orthanc:8042
      - EIP_PROFILE=prod
      - MYSQL_ADMIN_USER=root
      - MYSQL_ADMIN_USER_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - OPENMRS_DB_HOST=${OPENMRS_DB_HOST}
      - OPENMRS_DB_PORT=${OPENMRS_DB_PORT}
      - OPENMRS_DB_NAME=${OPENMRS_DB_NAME}
      - OPENMRS_DB_USER=${OPENMRS_DB_USER}
      - OPENMRS_DB_PASSWORD=${OPENMRS_DB_PASSWORD}
      - OPENMRS_USER=${OPENMRS_USER}
      - OPENMRS_PASSWORD=${OPENMRS_PASSWORD}
      - EIP_FHIR_RESOURCES=
      - EIP_FHIR_SERVER_URL=http://openmrs:8080/openmrs/ws/fhir2/R4
      - EIP_FHIR_USERNAME=${OPENMRS_USER}
      - EIP_FHIR_PASSWORD=${OPENMRS_PASSWORD}
      - ORTHANC_PUBLIC_URL=${SERVER_SCHEME}://${ORTHANC_HOSTNAME}
    image: mekomsolutions/eip-client
    networks:
      web:
      ozone:
        aliases:
          - eip-openmrs-orthanc
    restart: unless-stopped
    volumes:
      - "${EIP_OPENMRS_ORTHANC_ROUTES_PATH}:/eip-client/routes"
      - eip-home-orthanc:/eip-home

  mysql:
    environment:
      EIP_DB_NAME_ORTHANC: ${EIP_DB_NAME_ORTHANC}
      EIP_DB_USER_ORTHANC: ${EIP_DB_USER_ORTHANC}
      EIP_DB_PASSWORD_ORTHANC: ${EIP_DB_PASSWORD_ORTHANC}

volumes:
  eip-home-orthanc: ~
