services:

  # ERPNext - OpenMRS integration service
  eip-erpnext-openmrs:
    depends_on:
      env-substitution:
        condition: service_completed_successfully
      openmrs:
        condition: service_healthy
      mysql:
        condition: service_started
      erpnext:
        condition: service_started
    environment:
      - ERPNEXT_SERVER_URL=http://erpnext:8080/api
      - ERPNEXT_USERNAME=${ERPNEXT_USER}
      - ERPNEXT_PASSWORD=${ERPNEXT_PASSWORD}
      - ERPNEXT_OPENMRS_ENABLE_PATIENT_SYNC=false
      - EIP_DB_NAME_ERPNEXT=${EIP_DB_NAME_ERPNEXT}
      - EIP_DB_USER_ERPNEXT=${EIP_DB_USER_ERPNEXT}
      - EIP_DB_PASSWORD_ERPNEXT=${EIP_DB_PASSWORD_ERPNEXT}
      - EIP_PROFILE=prod
      - MYSQL_ADMIN_USER=root
      - MYSQL_ADMIN_USER_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - OPENMRS_DB_HOST=${OPENMRS_DB_HOST}
      - OPENMRS_DB_PORT=${OPENMRS_DB_PORT}
      - OPENMRS_DB_NAME=${OPENMRS_DB_NAME}
      - OPENMRS_DB_USER=${OPENMRS_DB_USER}
      - OPENMRS_DB_PASSWORD=${OPENMRS_DB_PASSWORD}
      - OPENMRS_BASEURL=http://openmrs:8080/openmrs
      - EIP_FHIR_RESOURCES=Patient,ServiceRequest,MedicationRequest,Encounter
      - EIP_FHIR_SERVER_URL=http://openmrs:8080/openmrs/ws/fhir2/R4
      - EIP_FHIR_USERNAME=${OPENMRS_USER}
      - EIP_FHIR_PASSWORD=${OPENMRS_PASSWORD}
    image: mekomsolutions/eip-client
    networks:
      ozone:
        aliases:
          - eip-client-erpnext
          - eip-erpnext-openmrs
    restart: unless-stopped
    volumes:
      - "${EIP_ERPNEXT_OPENMRS_ROUTES_PATH}:/eip-client/routes"
      - eip-home-erpnext:/eip-home

  mysql:
    environment:
      EIP_DB_NAME_ERPNEXT: ${EIP_DB_NAME_ERPNEXT}
      EIP_DB_USER_ERPNEXT: ${EIP_DB_USER_ERPNEXT}
      EIP_DB_PASSWORD_ERPNEXT: ${EIP_DB_PASSWORD_ERPNEXT}

volumes:
  eip-home-erpnext: ~
